name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: go build -o ncmlu_linux_amd64
    - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ncmlu_windows_amd64.exe
    - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ncmlu_darwin_amd64

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ncmlu_linux_amd64
          ncmlu_windows_amd64.exe
          ncmlu_darwin_amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
